### ISSUE TITLE
Rent not working

### ISSUE THREAD

**Issue by krustymk** [marcelo-mason/PreciousStones#1010]
I pop a sign on but it just reads and acts like a normal sign, no interacting with it by anyone..
I tried enabling commands and they dont work either 'command not recognised' (im op) (ps rent, ps buy)

here is the config for the problem block

http://pastebin.com/hVM4Jy3t

**Comment by marcelo-mason** [comment]
Weird just tested with your config and renting worked like normal.  What version of bukkit/sponge are you on now?

**Comment by krustymk** [comment]
Im on a different version now, off to work so i cant try but soon as i get home ill report back.

**Comment by krustymk** [comment]
Just tried it again, nothing, share seems to be working ok but not Rent or Buy.
If i type into the console '/ps rent' it gives a 'command not recognised' response

This version is about 3-4 days old, i have tried again over several versions at least

17:57:42This server is running CraftBukkit version git-Spigot-f9671b8-4d87c34 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are 4 version(s) behind

**Comment by marcelo-mason** [comment]
Set `settings.use-commands-to-rent: true` in config.  When that config option was added it was set to false by default.

**Comment by krustymk** [comment]
Yh, i set it to true to try the command before using the sign and failing. and then i got the 'command not recognised' warning.
Ive tried all 3 versions with clean servers now and getting the same issue (not the recent update, ive not tried that yet) So it must be my end i guess... (perhaps in the config?_) Ill update when i find the issue
Thanks

**Comment by marcelo-mason** [comment]
Wasn't on your end, I believe I found the issue.  I pushed a fix, that's the second commit there.  Try it out.

**Comment by krustymk** [comment]
I just tried everything clean.... was beginning to pull my hair out lol (what i have left... )
Trying it now
Thanks

**Comment by krustymk** [comment]
Sorry to be a noob but i dont know how to compile.. i just tried the one off the Jenkins site and its still the same

**Comment by krustymk** [comment]
I cant see a commit thats less than 2days old.. (your message is 18hrs old at this time)
So im probably looking in the wrong place.. 
Sorry to be a pain

**Comment by marcelo-mason** [comment]
Latest build on Jenkins should have done it.  Try getting latest from there again maybe you missed the last one that got built there.

**Comment by krustymk** [comment]
Last build  #1​4 10-Sep-2016 16:37
2days 1hr ago
Just checked and the file size is exactly the same as the previous i downloaded

**Comment by krustymk** [comment]
Could you check it got uploaded and built because i only see 1 recent build and your comment suggests there should be a least 2 recent builds and the one i have still doesnt work.

Thanks

**Comment by krustymk** [comment]
Still cant get this to work..
