### ISSUE TITLE
Not getting refund for all PS when breaking combined fields

### ISSUE THREAD

**Issue by PIE-yt** [marcelo-mason/PreciousStones#984]
When breaking PS that have been combined to increase volume, a refund is only issued for 1 of the field blocks rather than all of them, when broken using a tool.

Using "/ps take" however works as expected and refunds the cost for each of the PS in the combined field.

Tested with PS 10.3.3 and latest Spigot 1.9.4 (git-Spigot-798f32d-0cd0397).

Thanks so much for taking the time to continue supporting this awesome plugin, there's nothing else like it!

**Comment by marcelo-mason** [comment]
This should be fixed, reopen if not so.

**Comment by PIE-yt** [comment]
Hi,
This issue is still present in:
10.3.4 and Spigot 1.10 9 (git-Spigot-3ccadba-fb568fd)
Thanks for you time.

**Comment by marcelo-mason** [comment]
Wasn't able to test this yet, but that should do it.
